package y2020.day19;

import java.util.Arrays;

public interface Input {
    Notes sample = new Notes(
            Arrays.asList(new AndRule(new int[] { 4, 1, 5 }),
                    new OrRule(new AndRule(new int[] { 2, 3 }), new AndRule(new int[] { 3, 2 })),
                    new OrRule(new AndRule(new int[] { 4, 4 }), new AndRule(new int[] { 5, 5 })),
                    new OrRule(new AndRule(new int[] { 4, 5 }), new AndRule(new int[] { 5, 4 })), new CharRule('a'),
                    new CharRule('b')),

            new String[] { "ababbb", "bababa", "abbbab", "aaabbb", "aaaabbb", });

    Notes puzzle = new Notes(Arrays.asList(new AndRule(new int[] { 93, 93 }),
            new OrRule(new AndRule(new int[] { 40, 111 }), new AndRule(new int[] { 127, 70 })),
            new OrRule(new AndRule(new int[] { 127, 93 }), new AndRule(new int[] { 40, 40 })),
            new OrRule(new AndRule(new int[] { 127, 24 }), new AndRule(new int[] { 40, 58 })),
            new OrRule(new AndRule(new int[] { 127, 82 }), new AndRule(new int[] { 40, 75 })),
            new AndRule(new int[] { 93, 95 }),
            new OrRule(new AndRule(new int[] { 127, 64 }), new AndRule(new int[] { 40, 112 })),
            new OrRule(new AndRule(new int[] { 71, 40 }), new AndRule(new int[] { 106, 127 })),
            new OrRule(new AndRule(new int[] { 50, 40 }), new AndRule(new int[] { 126, 127 })),
            new AndRule(new int[] { 127, 65 }),
            new OrRule(new AndRule(new int[] { 65, 40 }), new AndRule(new int[] { 57, 127 })),
            new OrRule(new AndRule(new int[] { 127, 127 }), new AndRule(new int[] { 127, 40 })),
            new OrRule(new AndRule(new int[] { 98, 127 }), new AndRule(new int[] { 108, 40 })),
            new OrRule(new AndRule(new int[] { 40, 111 }), new AndRule(new int[] { 127, 34 })),
            new OrRule(new AndRule(new int[] { 65, 40 }), new AndRule(new int[] { 65, 127 })),
            new AndRule(new int[] { 42 }),
            new OrRule(new AndRule(new int[] { 44, 40 }), new AndRule(new int[] { 50, 127 })),
            new OrRule(new AndRule(new int[] { 127, 48 }), new AndRule(new int[] { 40, 13 })),
            new OrRule(new AndRule(new int[] { 36, 127 }), new AndRule(new int[] { 74, 40 })),
            new OrRule(new AndRule(new int[] { 127, 20 }), new AndRule(new int[] { 40, 114 })),
            new OrRule(new AndRule(new int[] { 50, 127 }), new AndRule(new int[] { 88, 40 })),
            new OrRule(new AndRule(new int[] { 29, 40 }), new AndRule(new int[] { 45, 127 })),
            new OrRule(new AndRule(new int[] { 127, 127 }), new AndRule(new int[] { 40, 127 })),
            new AndRule(new int[] { 40, 40 }),
            new OrRule(new AndRule(new int[] { 40, 89 }), new AndRule(new int[] { 127, 73 })),
            new OrRule(new AndRule(new int[] { 40, 69 }), new AndRule(new int[] { 127, 5 })),
            new OrRule(new AndRule(new int[] { 127, 122 }), new AndRule(new int[] { 40, 128 })),
            new OrRule(new AndRule(new int[] { 40, 30 }), new AndRule(new int[] { 127, 103 })),
            new OrRule(new AndRule(new int[] { 110, 40 }), new AndRule(new int[] { 53, 127 })),
            new OrRule(new AndRule(new int[] { 116, 127 }), new AndRule(new int[] { 59, 40 })),
            new OrRule(new AndRule(new int[] { 40, 40 }), new AndRule(new int[] { 127, 127 })),
            new AndRule(new int[] { 93, 90 }), new AndRule(new int[] { 42, 31 }),
            new OrRule(new AndRule(new int[] { 127, 61 }), new AndRule(new int[] { 40, 62 })),
            new OrRule(new AndRule(new int[] { 83, 127 }), new AndRule(new int[] { 12, 40 })),
            new OrRule(new AndRule(new int[] { 65, 127 }), new AndRule(new int[] { 62, 40 })),
            new OrRule(new AndRule(new int[] { 81, 127 }), new AndRule(new int[] { 91, 40 })),
            new AndRule(new int[] { 40, 57 }),
            new OrRule(new AndRule(new int[] { 61, 40 }), new AndRule(new int[] { 62, 127 })),
            new OrRule(new AndRule(new int[] { 40, 127 }), new AndRule(new int[] { 127, 40 })),
            new OrRule(new AndRule(new int[] { 40, 109 }), new AndRule(new int[] { 127, 107 })),
            new OrRule(new AndRule(new int[] { 9, 127 }), new AndRule(new int[] { 51, 40 })),
            new OrRule(new AndRule(new int[] { 25, 127 }), new AndRule(new int[] { 84, 40 })),
            new OrRule(new AndRule(new int[] { 104, 40 }), new AndRule(new int[] { 106, 127 })),
            new OrRule(new AndRule(new int[] { 43, 40 }), new AndRule(new int[] { 92, 127 })),
            new OrRule(new AndRule(new int[] { 93, 127 }), new AndRule(new int[] { 127, 40 })),
            new OrRule(new AndRule(new int[] { 106, 40 }), new AndRule(new int[] { 67, 127 })),
            new OrRule(new AndRule(new int[] { 95, 40 }), new AndRule(new int[] { 57, 127 })),
            new AndRule(new int[] { 40, 44 }),
            new OrRule(new AndRule(new int[] { 127, 55 }), new AndRule(new int[] { 40, 124 })),
            new OrRule(new AndRule(new int[] { 27, 40 }), new AndRule(new int[] { 13, 127 })),
            new OrRule(new AndRule(new int[] { 40, 41 }), new AndRule(new int[] { 127, 52 })),
            new OrRule(new AndRule(new int[] { 126, 127 }), new AndRule(new int[] { 61, 40 })),
            new OrRule(new AndRule(new int[] { 40, 40 }), new AndRule(new int[] { 40, 127 })),
            new OrRule(new AndRule(new int[] { 51, 40 }), new AndRule(new int[] { 95, 127 })),
            new OrRule(new AndRule(new int[] { 40, 127 }), new AndRule(new int[] { 93, 40 })),
            new OrRule(new AndRule(new int[] { 78, 127 }), new AndRule(new int[] { 129, 40 })),
            new OrRule(new AndRule(new int[] { 61, 127 }), new AndRule(new int[] { 50, 40 })),
            new AndRule(new int[] { 127, 40 }),
            new OrRule(new AndRule(new int[] { 82, 40 }), new AndRule(new int[] { 56, 127 })),
            new OrRule(new AndRule(new int[] { 127, 62 }), new AndRule(new int[] { 40, 61 })),
            new AndRule(new int[] { 127, 95 }),
            new OrRule(new AndRule(new int[] { 90, 127 }), new AndRule(new int[] { 61, 40 })), new CharRule('b'),
            new OrRule(new AndRule(new int[] { 15, 127 }), new AndRule(new int[] { 120, 40 })),
            new OrRule(new AndRule(new int[] { 40, 65 }), new AndRule(new int[] { 127, 50 })),
            new OrRule(new AndRule(new int[] { 50, 127 }), new AndRule(new int[] { 61, 40 })),
            new OrRule(new AndRule(new int[] { 40, 66 }), new AndRule(new int[] { 127, 16 })),
            new AndRule(new int[] { 40, 9 }),
            new OrRule(new AndRule(new int[] { 127, 88 }), new AndRule(new int[] { 40, 95 })),
            new OrRule(new AndRule(new int[] { 40, 94 }), new AndRule(new int[] { 127, 9 })),
            new OrRule(new AndRule(new int[] { 44, 127 }), new AndRule(new int[] { 61, 40 })),
            new OrRule(new AndRule(new int[] { 121, 127 }), new AndRule(new int[] { 130, 40 })),
            new OrRule(new AndRule(new int[] { 27, 40 }), new AndRule(new int[] { 56, 127 })),
            new OrRule(new AndRule(new int[] { 48, 40 }), new AndRule(new int[] { 97, 127 })),
            new OrRule(new AndRule(new int[] { 40, 95 }), new AndRule(new int[] { 127, 65 })),
            new OrRule(new AndRule(new int[] { 63, 40 }), new AndRule(new int[] { 7, 127 })),
            new OrRule(new AndRule(new int[] { 123, 127 }), new AndRule(new int[] { 36, 40 })),
            new OrRule(new AndRule(new int[] { 40, 44 }), new AndRule(new int[] { 127, 65 })),
            new AndRule(new int[] { 40, 127 }),
            new OrRule(new AndRule(new int[] { 40, 125 }), new AndRule(new int[] { 127, 72 })),
            new OrRule(new AndRule(new int[] { 65, 127 }), new AndRule(new int[] { 94, 40 })),
            new OrRule(new AndRule(new int[] { 127, 65 }), new AndRule(new int[] { 40, 57 })),
            new OrRule(new AndRule(new int[] { 40, 126 }), new AndRule(new int[] { 127, 65 })),
            new OrRule(new AndRule(new int[] { 9, 127 }), new AndRule(new int[] { 126, 40 })),
            new OrRule(new AndRule(new int[] { 127, 35 }), new AndRule(new int[] { 40, 88 })),
            new OrRule(new AndRule(new int[] { 22, 127 }), new AndRule(new int[] { 100, 40 })),
            new OrRule(new AndRule(new int[] { 40, 90 }), new AndRule(new int[] { 127, 65 })),
            new OrRule(new AndRule(new int[] { 9, 127 }), new AndRule(new int[] { 61, 40 })),
            new OrRule(new AndRule(new int[] { 40, 82 }), new AndRule(new int[] { 127, 39 })),
            new OrRule(new AndRule(new int[] { 21, 40 }), new AndRule(new int[] { 101, 127 })),
            new OrRule(new AndRule(new int[] { 126, 127 }), new AndRule(new int[] { 44, 40 })),
            new OrRule(new AndRule(new int[] { 127, 54 }), new AndRule(new int[] { 40, 37 })),
            new OrRule(new AndRule(new int[] { 127, 61 }), new AndRule(new int[] { 40, 50 })),
            new OrRule(new AndRule(new int[] { 40, 119 }), new AndRule(new int[] { 127, 99 })),
            new OrRule(new AndRule(new int[] { 77, 40 }), new AndRule(new int[] { 105, 127 })),
            new OrRule(new AndRule(new int[] { 60, 40 }), new AndRule(new int[] { 106, 127 })),
            new OrRule(new AndRule(new int[] { 38, 40 }), new AndRule(new int[] { 2, 127 })),
            new OrRule(new AndRule(new int[] { 46, 40 }), new AndRule(new int[] { 49, 127 })),
            new OrRule(new AndRule(new int[] { 44, 127 }), new AndRule(new int[] { 95, 40 })),
            new OrRule(new AndRule(new int[] { 14, 40 }), new AndRule(new int[] { 79, 127 })),
            new OrRule(new AndRule(new int[] { 127, 65 }), new AndRule(new int[] { 40, 65 })),
            new OrRule(new AndRule(new int[] { 90, 127 }), new AndRule(new int[] { 95, 40 })),
            new OrRule(new AndRule(new int[] { 127, 18 }), new AndRule(new int[] { 40, 85 })),
            new OrRule(new AndRule(new int[] { 40, 80 }), new AndRule(new int[] { 127, 4 })),
            new AndRule(new int[] { 93, 62 }),
            new OrRule(new AndRule(new int[] { 93, 127 }), new AndRule(new int[] { 40, 40 })),
            new OrRule(new AndRule(new int[] { 35, 40 }), new AndRule(new int[] { 65, 127 })),
            new OrRule(new AndRule(new int[] { 117, 127 }), new AndRule(new int[] { 46, 40 })),
            new AndRule(new int[] { 127, 127 }),
            new OrRule(new AndRule(new int[] { 90, 40 }), new AndRule(new int[] { 88, 127 })),
            new AndRule(new int[] { 8, 11 }),
            new OrRule(new AndRule(new int[] { 40, 102 }), new AndRule(new int[] { 127, 115 })),
            new OrRule(new AndRule(new int[] { 96, 40 }), new AndRule(new int[] { 26, 127 })),
            new OrRule(new AndRule(new int[] { 10, 40 }), new AndRule(new int[] { 24, 127 })),
            new OrRule(new AndRule(new int[] { 50, 127 }), new AndRule(new int[] { 126, 40 })),
            new OrRule(new AndRule(new int[] { 23, 127 }), new AndRule(new int[] { 87, 40 })),
            new OrRule(new AndRule(new int[] { 1, 40 }), new AndRule(new int[] { 28, 127 })), new CharRule('a'),
            new OrRule(new AndRule(new int[] { 65, 40 }), new AndRule(new int[] { 50, 127 })),
            new OrRule(new AndRule(new int[] { 40, 33 }), new AndRule(new int[] { 127, 56 })),
            new OrRule(new AndRule(new int[] { 57, 127 }), new AndRule(new int[] { 35, 40 })),
            new OrRule(new AndRule(new int[] { 113, 127 }), new AndRule(new int[] { 3, 40 })),
            new OrRule(new AndRule(new int[] { 127, 9 }), new AndRule(new int[] { 40, 126 })),
            new OrRule(new AndRule(new int[] { 68, 40 }), new AndRule(new int[] { 47, 127 })),
            new OrRule(new AndRule(new int[] { 86, 40 }), new AndRule(new int[] { 76, 127 })),
            new OrRule(new AndRule(new int[] { 127 }), new AndRule(new int[] { 40 })),
            new OrRule(new AndRule(new int[] { 84, 127 }), new AndRule(new int[] { 118, 40 })),
            new OrRule(new AndRule(new int[] { 88, 127 }), new AndRule(new int[] { 65, 40 })),
            new OrRule(new AndRule(new int[] { 17, 40 }), new AndRule(new int[] { 19, 127 })),
            new OrRule(new AndRule(new int[] { 40, 6 }), new AndRule(new int[] { 127, 32 }))),

            new String[] { "aabbbabaabbbbababaaababbaaaaaaaa", "babaabbbaaaabbbbaababbabbabaaaabbabaabba",
                    "abbbaabbbbaabababbaaaababbabbbba", "bbaabbabbbaaabbbbbaaaaab", "aaabbaaaaabbabbaabaababa",
                    "bbabbabbaabbabbbbbabbaab",
                    "aababbaabbbabaaabbababbbabaaabbbbbaabaaabbbbaaabaabbabbaaabbabaabbbaaaababbbabaaaabbabbb",
                    "abaabbaaaaaaababbbbbaaaa", "abaababaabaaabbbabababaabbaaababbabbbbbabbbabababbabbabbabbbbaab",
                    "bbabbababbbbbabbbabbaaba", "babbbaaababbbbababaaabbbbaabbbab", "babaabbbbbababaabbbabbaa",
                    "aaaaaabbaaabbabaabaabaaa", "aabbbbbbaaababbaababbbaaaaabababbaabbbab",
                    "aabbbbbabaabbabaaababbabbbaaabaa", "babbbbbabbbaababaabaabbaaabbbbbbaaaaaaaa",
                    "aabbbbaaaaaaaabbabbbbbbaaabbaabaaabbaaaabbababba", "ababaabbbaabbbbaabbbabab",
                    "aaabaabbaaabaaaaaaaabbba", "aabbbabbbbbababbbababaaaabbabbbb", "bbbbabaabbaabbbabababbab",
                    "bbbababbbbaaabbbbbbaaaba", "bbbabaaaabaabbaaaababbaa", "abbaaabbbbbabbbbbabababa",
                    "baaabbabababbabbabbaabab", "babaabbbabbaaaabbbabaabaaabaaaaaabbabbab",
                    "ababbbabbbbbbabbaaabaaabaaaabbaaabbbaabb", "abbbaabababaaaababbaaaaaaabababaaaababbb",
                    "bababaaabaaaabbbaaababbb", "aaabaaabbaabbabaabababbbabbbbbaababbabaa",
                    "abbbbabbbaaaaaabababbbabbbbaabbbaabababa", "aabaaabaabaabbbbbbaabbbabaaaaaabbababbbbaaaabaaa",
                    "babbaabbaabaababaaaaaaab", "baabbababbabababbbaabaabaabaabbaaababbaaaaaabbaa",
                    "aabbaaaabaabbbbaabbbbaab", "bbaaabbaababaabaaababaababbabaab",
                    "aaabbaabababbbbaaabababbabbbabbaaaabababbabaaaaaabaabaaaaaaabbbabaaaabaa",
                    "babbbbbbbaabaaaaabababab", "abbaaaaabaaabbaaababaabbbababaaabbbababaaaabbbaabaabaaba",
                    "aaaaaabbbbbababbaaabaaababbabbababababab", "bbbabaaabbaababbabaababaaaabbbbbaababbba",
                    "aaabbbbabbbbabaababbaaabababbaaabaaabbaabababaabaabbbaba", "baabbabababbbbbaaababbabbabbbabb",
                    "bbbaababbabaabbabbbaabababababbbbbabaabb",
                    "bababbababbaabababaababbbabaabbbbbbaababbbaabbaabbaaaabaabaaaaba", "abbbaaaaaabababbbbaaabab",
                    "bbaabbbaabaabbbaabaaabab",
                    "aabaabababbaabaaabbabaaaabbabbaaaababbbaaaabbabbbaaaabbbbaaaabbbbaabbabb",
                    "aababbbbababbababbaabbababaababaaaaaaaabbaaaabbabaababbbabbbabaabbaababbbbaababb",
                    "abbaaaabbbabbabaababaaaa", "babbaaaaaaababbababaaaaa", "bbbbaabbbbaaabbabbaababa",
                    "ababbbabaabbbabbabaababa", "abbababbaabbbbbaabbbbbabaaabbbab",
                    "aaabbbaaababaabbaabababbababaaaaaaabaabaabbaabbb", "bbaabbabbaabbbaabbbbabba",
                    "aaaaaabbabbbaaaabaabaabbabbbbaba", "bbbbbabbababbbaaabaaabbbbbbbabbaaaaaabbb",
                    "abaaababaabaaababbaaaaaaaaaabaaababbbbbbbbabbaaaaabbaabbababbababaaaaababaaaaabbaaabbabbbbabbbaa",
                    "aabbbbaabbbbbabbbbbabbaa", "bbabababaabaaaabaaaabbaa",
                    "babbbbaabaababbbbababbaaabaaaabaaaabbbabbabbbabbbbbbbbaa",
                    "abbbabbbabbbaaaabaaaabbbabbbbababbbbaaaabbaababbababbbba", "bbbabaaaabbbaaaaaabbbbba",
                    "aaaaaabbaaaaaabaaabbaaba", "babbbabaaababaabbababbba", "abbbbabbbaababaabaaaaababababbab",
                    "bbbbaabbbbababaababaabaa", "baabbaabbabbaaaabababaaaaaabbaababbaabaa", "baababaabaababbabbbbabbb",
                    "aabbabbababaabbbabaababb", "abaabbbbaaababaaabbaabab", "babbbababbbbbabbabaabbbaababbbaabaabaaaa",
                    "abbababbbbbbabbabaabaabbaabaabbaababaababaaabaaabbababababbaaaab",
                    "baaabbaababbbabbabbabbbaaaaaaaababbbaabaaaabaabaababaabbbbabbaab",
                    "baaaaaabbaaaaabbbaabaaaabaabbbabbbbababaabaaaaaabbaaaababaaaaaabaaaabbaa",
                    "abaabbbbababbbabaabaabbbbbbaaabaaababbaaabababab", "ababaaabaabaabbbbbbbaaaa",
                    "baaabbabbabbbaaaaababbbaaabbbaaa", "baabababbbbabbbbbbabaaab", "abbbaaababaabbbababaaaba",
                    "babbaaabaaabbababbaaaaabbbbbbabbbbbaaabaaaababaaaaabbaba", "aabbbaaabababbabbabaaaaa",
                    "bbaaabbbabaabaabbababbbbbbbbabbbbabbabaabbbbbaaaaaaabbab", "abaaaabbabaaaaaaaaababbb",
                    "baababaabbbbababbbbaaaaa", "babbaaaaaabaabababaabaab", "babbbbaabaabbbbbbaaaabbabaabaaaa",
                    "bbbbaabbaaababbabaababbb", "abbbaaaabbbabbababaabbab",
                    "bbaaaabbbbbaababaaaabaababaabbbabbbaaababbaabaaabaababaaaababaabbbbabaabbabaaababaaaaabb",
                    "aaabbaaaaaabaabaaabbaaaabbaaabbabababbaabbbabbba",
                    "aaabaaabaabababbbabaabbbbbaaabbaaabbbbabbbabbbabbbbaaaab", "abbbabbbabbbbbbaaaaaabbb",
                    "ababaababbbaaabbabababba", "aabbaabaaababbabbaaababa",
                    "ababaaabaaaabaabbbabababbbbaabaaaaababbabbbbaabababbaababbbbabba", "babbbbbbabaaaaaaababbbba",
                    "aaabbbbababbbaaaabaaaaba", "ababaababababaaaaabaabbbbababaabaabbbbbbbabaabbbaabababaabaabbab",
                    "bbbbbbababaaaabbbbababba", "babaabbabbaabbbabbaaabab", "aaabaabbababaababbabbbbabaaabbba",
                    "bababaabbaabaaaabbababaabbaabaaa", "abbbbbbaaabaabbbabaababb",
                    "babababbbbababbbbbaabbabbaababaabbbababbbbbbababbabbababaababbaababbabaa",
                    "bbbabbabbabbbaaabbababbbabbbaaaabbbbbbabbbbbbababbbbabba",
                    "baaabaaaaabaabbaaaabaabbbaaabbaaabbaaaabbbbaaabbabababababababba",
                    "ababbaaaabaaaabbabbbaaabbaabbaaaaabaabbb", "bbaabaabababbabbabbaaaabbabbbababaababaa",
                    "bbababaababaabbbaabbbbabbbbabababababbab",
                    "baababaabbaabbaaaaabaaaabaabbabaabaaabaabaaaaaaaaabbbbba",
                    "aaababbbaabaaabaaababaaaabababbabbaabaaabbbaabaabaabaaababaaababbabababa",
                    "abaaaaaabaabbbbbbababaaaaabaaabaabbbaababbbbabba",
                    "bbababaaaababaabababbbabaaabbabbbaaaabbbbaaaababbaaababa", "baababababbbabaaaaaaabba",
                    "aaabbabaaaabbabbaaabbbbbabaaabab", "baabbaaaabbbbabbabaabbbbbaabbabb",
                    "abaaabbbbabbbbabaababbbaabbaaabaabaabbbaabbbbaab", "ababbabbabaabbbaabbbbbab",
                    "bbababbbabaabababbababaababbbbaaaaaaabbaaabbaaabaaaabaaaaaaaababaaaaaaab",
                    "aabbbbabbbabbabbbbbaaaba", "abababaaabbababbabaabaaa", "babbbbbabaaabaabbaaabbbb",
                    "abaabbaabaabaaaabaabaaaabbaababa", "aababaabbbaabaaabbbaabba", "bbababbbaababaabbbbaabbb",
                    "baaabaabaaaabaabbababbbb", "bbaabaabbaabbaaabaaabbbb", "aaababbaababaababbaaaaba",
                    "babbbbbbabbbaababaaabbba", "babaabbbaababaababaabbab", "aaaabbbbababaababbaaabaa",
                    "aaaaaabababbbbaababbaaababbabbbb", "aaabaaaaaabbabaabbaabaaa", "aaaaaabaaaababaaabaaabaa",
                    "baaabaaaaabaabbbbbaaabba", "abaaaaababaaaabaaaabbbbaaabbbbaaaabaabbaabaababbbabbbaab",
                    "baaaaaabbaaaabaaaaaaaabababababbaabbaababababbbbaaaaabaaabbbbbba",
                    "aaababaabbaaabaabbabbbabbbaabaaa", "bbaaabaaaaaaaaaaaaaaaaababbbabaa", "bbbbbaaabbbaaaaabbbaabba",
                    "baaabbabbaaaaaabaababbaaabaababaaaaaababaaaaabaababbabba", "bbbabbbbbbaabbabaaaabbba",
                    "aabaabbbabbbbabbaababbaabaaaabaaaabbbbaaaaabbbaaaaabbbba", "abaaaaaabaabbaabbbaaabbbbabaaaaa",
                    "aaabbbbbbaabbbbabbbabaab", "baabbaabaaabaabaabaaaaaaabababba", "aababbabaaabaabbabbbabba",
                    "aababaababbbbabbaabaabbaaabababaaaabbbab",
                    "abbaaabbbbbbabbabbaaaabbbbaaabbbbbaaaaabbaabbaaabbaababb", "aabaabbbababaabaabaabbbbaabbaabb",
                    "bbbabaabaaabbaabbbbaabbbbaabaaabbbabbbbabbaaaaabbaababaaaaabbaaabbaaaaaa",
                    "baaaaaabbabbbbbbbbaabbabaabbbaab", "bbbabbabaaaabbbaaabaabaabaaabababbbabbbbababaaba",
                    "aaaaaabbaabaaabaabaababb", "abbbaababaabbabaababaaaa", "babbaaabbbbbababbabaabba",
                    "abbabbbaaaaabaaaaabbababbbbbbaabbaabbaaaaaabbabbbbbaaaabaabbbaababaaabab",
                    "aaabbbbbbaaabbaabbabaaab", "aaabbabaaaabaabbaabaaabb", "bbabbbaaaabaabbababaabbaaabababaaabbbaab",
                    "aabbaabaabbaaabaababbababbbaabaababbaababbbbaaba", "bbababbbbaaaabbbaabaababbaaaabab",
                    "baababaabbaaababbbaabaaaabaabbbaabbbaaaaaaabbabababaabbbbababbabbbaaabbb",
                    "babaaaabababbaabbbbaaaab", "bbababbbbaabbbbbbabbabab", "ababbbaabbbaababaaaaaaab",
                    "aababbabbabbbaaababbaaaababbabbbbbaababb", "aaabbaaaaabbabbaaabbabaaabbaabaa",
                    "abbaaabaabaaaabbaabaababbabbbaab", "aaabbaaababbaabababbabba", "aabbaabaaaabbbbbaabbbaba",
                    "abbaaabbbaaaabbabbabbbba", "baaaabbaaababaababababab", "bababaababbbbbbaabbabaaa",
                    "abbaaaabbbabbababbbaabaaabbbbabbaaabbbaa", "bbabbbaaaabbbbaaaaaaaaaa", "babbbbbbaaabbabaabbabbbb",
                    "abbaaabbbbabbabbaaabbaabaaaaaabbbbbbbbabbaabbaab", "bbbbabaababbbaaabbaaabbbaabbaababaabaaba",
                    "baabbbabbbbbbbbabbbabaabaabaaabb", "aababaabaaabbbbabbbbbaaa", "babababbaabaababbaaaaaaa",
                    "bbbaabaabbbaaaaabbabbbba",
                    "abbabaabaabaaaaabaaaabbbbaaabaaaaaaaabbaaababbbbbbaabbaabbbbaaabbbbbabbb",
                    "baabbaabbabbbbaabbaabbaabbabbbaabaabbabb", "baaabaabbabbabbbaaaaaaaabbaabaaaaaababbb",
                    "baabaabbbbbabaaabbabaabbbbbabaabbbbbabbaaaababbb", "bbbbbbabbaababbaaaabbaaabaababbb",
                    "babaabbbaabbbbaabababbbbbbbaabbaaaaaaaab", "aabaaaabbabbaabbabbaabbbaaaabbabaabababa",
                    "aaaaaabaaabbabaabbaabaabaaaabaab", "aaabbbbaaaababaabaaabbaaaaaaaabbbabbbaab",
                    "abbbbabbaabbbabbabbbaababbbababaabbabaab", "bbabbbaabaabbaababaaabab", "aababaabaaabbbbbbabaabaa",
                    "aaababbaabbaaabbbaabbbab",
                    "baabbbbaabbabaababbababbbbabaaabbbbbabaabbaabbaabaababaabbbbabbbbaabbaba",
                    "bbaaabbbbabaabbababbbbbbbaabbbbabbbaaaabaaaabbba", "bbabababbabbbbbaaaaaabbaaaaabbab",
                    "bbaabaabbaabbbbbbbaabaabbabbaabaaabababa", "ababbabbaabbbbbbbbabbbbb",
                    "aaaaabbbbbabaabbabbabbabbababbaa", "aabbabaaaabbaabaabaaaaab",
                    "ababbbabaabaaaababaaabbbbaabbbbabbbbaaba", "ababbabbaabaabbabaabbbbbaaaaaabbaabaaabb",
                    "bbbbbbabbaabbaababbabaaa", "abbbaaaaaaabbababaabbaabbaabaabbaaaabaaa",
                    "baaaaaabbbaaaabbabaabbbabaabababbabaaaabbaabbbbbbabbbabb",
                    "bbaabbbabbbabbaabbaabbbaababababbbababaaaababbbbbaabbbbaababaaababaaabbabababaaaabbbaaaa",
                    "aabbbbaabbbaabaababaababbabbabaaabbbbaabbbabaabb", "bbababaaaaabbabaaabaaabb",
                    "ababababbabbbabababbbaaababababaaaababaaabbbabbbababbbaabaabbbaa",
                    "baaaabaaaaaaababbbabbbbabbaaabaaabaabaabaaababbbbaaabbbbaabaaaba",
                    "baabbaaaaabababbbaabaaaababaabaaaaabababbbabbaaa", "bbbaaaabbbaaaaabbaabbbabaabbaabbabbbabab",
                    "baabbbbbaababaaaabbbabaaabbbbaaaabababba", "ababbaababbbaaaaaaaaabbb",
                    "abbbabbbabbbabaaabbaaabbbbbabaaabbaaaaba", "aaabaabaaaabbabaabbaabaa",
                    "aabababaabbabababaaaaabbbbbbaabbaabbbbbbabbaabbbbaabaaabbbbbbaabbbaabbbb",
                    "baabbbaabaabbabaabababaaabaaaaab", "abababaabbabababbbbaabba", "aaabbaaabaabaaabababbaababbababa",
                    "aaabbbbababbbababaaababb", "babbaaaaaaabbabaaabbaaabbbabbbbb",
                    "baabbaaabbaabbabaaabbabbaaabbbbabaabbbbbabbbbbaaaaaaababbabbbabb",
                    "bbbbaaabbaabaaabbababbababaababaaabaabaa", "baabbbbababbbabababbbaab", "babbbbaaaabaabababbabbbb",
                    "abababaababaaababaabaaabbbbbbabbbbababbabbababaabbbaaaaa",
                    "aaabaabababbbbabbbaaabbaaaaabaabbbbaababbaaaaaaa", "bbaaabbbaaababbabbabaabb",
                    "bbbaabaaaabababbababaaaa", "baababaaaabbabbaababababaaabbaaaabbaabbbbbaaaaba",
                    "aabaaabaaaaabaabaaabaabbbaaaaaaababbaaba", "abababaaabaaabaaabaababa", "babbaabbababaabbaaabbbaa",
                    "abbaaaaabaaabbaabbbaabba",
                    "bbabaaaabaabaaabbbbbaabbabbabababaaababbbaabbaabbbabbabaaabbabaaababbabbbabbbabb",
                    "ababbabbaaababbabababbbbbbabaabbbbbbabbaaabbbaab",
                    "aabababaababbabbbaaababaaabbabbaabbbbbaabbabbbbaaaababbababbbbba", "aabbabbbbbaaabbabaaabbba",
                    "ababbaababbaaaaabbabababbbaabbaa", "bbbabbbbbbabababaaabbbba", "abbaaababababbaabaaaaabb",
                    "aabbababbbababababbaabab", "bbaabbabaababbbaabababab", "baabababaabbabbabbabbbab",
                    "bbababaaaabbbbbbbbabbbba", "ababaababbbaaabbbabaabaa", "baaaabbbbaabbaaaabbbaaabbabbbabbabaabbab",
                    "aabbbbbbabbaababbabbbaaabbbaabbbabaababa", "baababaabababaaababbbbabbaaababa",
                    "babababbbaabbbbbbbaaabaa", "babbbaabbaaaababbabaabaabbbaaaaaaaababaa", "aabbbbbbbabbbbbbabaabbab",
                    "aaaabbbbaabaabababbbabba", "aabaababaabaababbbbaaaab", "abaabbbbababbaababbbbbbaabababab",
                    "babbbbbbabbababbaababbbb", "abbabbbabaabbbaabbabbbbaaabbbaaaabbababa",
                    "bababbabaaabababaabbabaaabababbbabbaaaababbbabbaaababaabababbbaaaaabbaaa",
                    "aabbababaabbaababbaaabbabbabbbaaabaaaabbaaaabaaaaabbbaaa", "babbbbbbaabbaaaabaabbbab",
                    "baabaaaabbaaaabbabaaaabbabaaabbbaabbbbaababbbabb", "bbaabbabbaabbaaabaaaabaa",
                    "bababaababaaaaaaaabaababaabbabaababbbbbabbbabaabbbbbbaab", "baababbabaababbabaaaaabb",
                    "baabbbaaaaaabbbabaaaaaaaaabbbaabbaabaabaabaababa", "aabbaabaaababbbabbbabbabaababbbbabbbaabb",
                    "abbbbababbabbaabaabaabaaaaaabbbbaababbbaaabbabbb", "abaaabbbabbababbaabbbaaa",
                    "bbabbabaaababbbaabbbaabaaabbbbbbabbabaaabbbbbabababbbabb",
                    "aabaababbbbaabaaaaaabbbbabbaaaaabaababbbbababbbaabaababababaabaa",
                    "aabaabaabbbababaabbbabbaaababbbb", "aaaaabbabbababaaabaababaaaaaabaaaababbba",
                    "bbaaaaababbbbababaabababaababbabbbabbbabbbaaabbaaaabbaababbbaababbaabbaabbbaabaa",
                    "babaabbbbbabbabababbaaaabbbabbaa", "aaabaaaaaaaababaabbbbbbaaaaabbbabbbaabbaaaabbbaa",
                    "babbbbabababaaabaabbbaaa", "bbbbaaabbbbbbabbbbaabbabaabbabababaabaab",
                    "bbabbbbbbbaabbbbbaaaaabbbbbababbbaaababbabaababbabbabbaabaabaaab",
                    "abbabbbaaaabbabbabbbaabaaabaaabbabbbbbaa", "aaabbaaaabababaaaaababbaaababbbabbbbababaaaaabab",
                    "abaabbaaaaababbabababbbb", "aaabaabbaababaaaabbabbbabaaabbbbbbbbbaba", "bbbbaaabbbabbabaabbbbaaa",
                    "ababaaabbbababababbbabba", "bbbabbbbaaaaaabbaaaababa", "baabbbbbbbbbaaabbababbaa",
                    "aaabbbabbababababaaaaaaa", "baabbbabbababbabaaabbaababbaaabbabbbbbab", "bbabbababaabababbbaaabaa",
                    "bbabbabaaabbaababbabaababbbaabbbabaaaaba", "abaabbaaabbaaabaabbaaaaa",
                    "baabbbbaaaabbbabbaabbbbbababbbaabbbbbbbbbbaabaababaabaab", "aabbabaababaabbaabbbabba",
                    "abbbabaabababaabababaaaa", "bbaabbabbbabbbaabbbaabbb",
                    "baaabbabaabbabbaabbbabbbabbabbbabaabbabababbabbbaabbaaabbbabaaaaaabababababababa",
                    "aabaaaabbbbabaababbaabbbaaabbaaababbbbabaaaabbbaaabbbbabbaabaabb", "abaabaaabababbabaaaababb",
                    "babaabbbaaababbbbbabaaba", "abbbbabbbaabbbbaabbabaaa", "aabbabaabaabbbaababbabaa",
                    "babbbbbbbaabaaababaaabab", "ababbaaabbaabbaababababbbbababbbbbbbabbbaaaaaaab",
                    "baaaaabaababbbabbabaaaaaaababbabaaababbabbababbbbabaabba", "baaaaabaaabababbbabaaaaa",
                    "bbaaabbababbbbbbaaabaaabbaaaabab", "aaaaaababbabababbbaababa", "abbabbbabaabaaabbbbbbbba",
                    "abbbbabbbabbbabaabaaabbbabbbbabbaaabbbabaaaaabba",
                    "bbbabaabbabbaababaaaabaabaabbabbaababbbabbaaaaabbbbaababaaababbb", "bbaaaabbabababbbbbbbbaab",
                    "baabaaabbabbaabbaabababa", "babbbbbabaabaabbbabaaaaa", "babbbaaaababaabbabbaaaaaaabbbbab",
                    "baaabbabbaabaabbabbbaaaaaaaaaabbaaabbbbbbabaabab", "ababaaaaaaaaaaaaababaaaaabaaabab",
                    "bbbbbbabaababaabbbaabaabbbababba", "bababaaaaaabaabbbabababa", "bbabababaaabbabaaabbababbbbababb",
                    "baabbabaabaabbbabbbaababaaabbabbbabbabbabbabaaaa",
                    "abbbabbaabbaabbabbbaabbbbabbbbbaaabbbaabaababbababaaababababaaabbbabbbab",
                    "ababbaabbabbaabaabbbbbbbbabaabaabbaaaaabbabababb",
                    "abababaabaaaaababaababaaabbaaababbbbabbbbbabaabbabaaababaabbaabbaabaaabb",
                    "ababbaababbaaaaabaabbbbbaaaaabaaabbababbbababbbababbaaabbaabbaba",
                    "aabbabbbaaabaabbabaabbbbbbbbbaab", "baaaabbaaaababaaabbaabbb",
                    "aababaabbaaabbaaaaaabaababaabbbbbbbbbaaa",
                    "bbaabaabbabaaabbbababbababbbabbaaabaabbaabbaaaaaabbbaababbbbabaabbaaaaabbababbaa",
                    "aababaabaababaababbaabab", "bbaaababbbbaaaaaabbaabababaaababbbbaabaa", "abbaabbaabbaabbababbabab",
                    "babbabaabababaabaababbaaabaabaabaaabaabbabbababbaaabbbbaabbaaaaaaababaab",
                    "ababaaababbbbbbaaababbbb", "bbbbbbbababaabaaabbabaab", "baaabaabbabbbbaaaaaaabbb",
                    "ababaabbaaabbabbaaaaabab", "bbaabbbaaaaabbabaabbbaba",
                    "abbaaabbbbbbbabbabaabbaababbbbbbbabbababbababbbb", "baaaabbaabbaaaabaabbabababaaaaaaabbaabaa",
                    "abbabbbaaaabbaaaabababab", "aabaababababaabbbabbabaa", "abaaaabbbaabaaabaaabbbaa",
                    "aabbabbbbbbaaabbaaaabbab", "ababaabbaabbaaaabbaaaaab", "abbbbbaabbbbbbbaaabbaabb",
                    "abaabbbaaaabbbbbabaabbab", "babaaabbbabbbbaabaaaaabbbbbabbaabaabbaaa", "babaabbbbaababaaaabbaaab",
                    "aaabaaaaaabbbababbbaabbabbabbaab", "aabbabaaababbbaabbaaabab", "abbaaaabbabababbbbbbbbbb",
                    "baaabbaaababaaaaababaabbbbabbbaabbbaababbabbbbabbaaaabbaaabababbabaaabbababaaaabbaababbb",
                    "ababaaabbbbabbbbbaabbabaaaaaabaa", "aaababbaabbababbaababaaabaababbabbbaabaababbabba",
                    "baabbbbbabbbbbbaabaabbbbbaaaabbaaabbaabaaabaaabaabaabbab",
                    "aabbbbbaaabababbbbbaaabaaababbaabababaabbaabababbaabbabbaabaababbbabbaabaabbaaba",
                    "baabaaaaaaaabaababbaabbb", "aabaabbbbabbaabbbaababbb", "abbaaabaaabbabbaaaaaaabbaaaaabab",
                    "baabbbbaaaabaaabaaababaaaabbaabb", "abbabbbaabababaaababbbba", "aaaabbbbbbaabbabaabbaabb",
                    "baabaaababbbaabaabbbbbaa", "abbaaabaaabaababbbabaaaa",
                    "bbababaaaabaaaabbabbbbbbababbbbbbbbbaabaabbbbaba", "aabbbbaaaaaaaababaaababa",
                    "bbbabbabaabaaaabbababaabbbaabaabbbaaaaaaaabbbaabbbbabaab",
                    "babababaabbbababbbbbbaaababaaaababbaaabababbaaaaaababbbabbbabaabbaaaababaaaaabbb",
                    "aaababbaaabaaabababbaabbbbabababababaaabbbababba", "bbaabbabababaababaaaaaaa",
                    "bbbaababbabbbbbabbbbaaaa", "baabbaababbabbbabbaaabbbbbbbaabbbaabaaaabbaabbbb",
                    "ababbbababaabbaabababbab", "aaabbaaaabbaaabbabbaabab",
                    "bbaabaaaabaabbbbbbbaabaabbbbbaaabababbbaabbabbbbaababbab", "babbbabababbbababbbabbba",
                    "abbbbabbbbababaaabaabaab", "abababbbabbbabaabbbbababababbabaaaabaaaaaaaaaababbbbbaabbaaabbbb",
                    "babaabbaaaaabbbbabbbbaab", "baabaabbbabaaaabaabbababbbaaabaa",
                    "baaaaaababaaaaaabbaabbabaabbaaaabaaaababbaabaaba", "aabbaaaaabaabbbbabaaaaab",
                    "aaababbbabaababbabbbaabbbababaaaaaabbabbbbabbabaabababbbbbbababbabbbbaabbabababb", });
}
